# Generated by Django 2.2 on 2019-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.URLField(blank='True'),
        ),
    ]
